/* ---------------------------------------------------------------------------
   The seeded register of federated applications, and how a status reads.

   Kept free of heavier imports: the navigation badge reads this on every page,
   so it must not pull the connector model into the console's first load. A
   record stores only the connection values it sets; the form lays them over
   the connector's full field set.
   ------------------------------------------------------------------------- */

export const STATUS = {
  Healthy: { label: 'Healthy', tone: 'ok' },
  Pending: { label: 'First sync queued', tone: 'acc' },
  Degraded: { label: 'Degraded', tone: 'warn' },
  Failed: { label: 'Failed', tone: 'bad' },
  Paused: { label: 'Paused', tone: 'mut' },
  Manual: { label: 'Tracked only', tone: 'mut' },
}

export const statusOf = (r) => STATUS[r.status] || STATUS.Healthy

export const needsAttention = (r) => r.status === 'Failed' || r.status === 'Degraded'

export const FEDERATIONS = [
  {
    id: 1,
    name: 'HRMS_EMPLOYEES',
    displayName: 'HRMS Employee Store',
    description: 'Employee master records from the HRMS database, federated into the corporate directory.',
    connector: 'postgres',
    ldapAppId: 1,
    ouDn: 'ou=people,dc=tanflow,dc=com',
    operations: { create: true, update: true, remove: false, updateExisting: true },
    connection: { host: 'hrms-db.tanflow.internal', port: '5432', database: 'hrms', username: 'idam_fed', password: 'stored', accountTable: 'public.employees' },
    schedule: 'Hourly',
    matchKey: 'empCode',
    status: 'Healthy',
    users: 1284,
    lastSyncMins: 18,
    createdOn: '2026-03-12',
    createdBy: 'SHUBHAM_JAIN',
  },
  {
    id: 2,
    name: 'AD_EMEA',
    displayName: 'EMEA Active Directory',
    description: 'Regional forest for the EMEA offices, federated into the Windows forest replica.',
    connector: 'ad',
    ldapAppId: 3,
    ouDn: 'ou=people,dc=corp,dc=tanflow,dc=com',
    operations: { create: true, update: true, remove: true, updateExisting: false },
    connection: { connectionUrl: 'ldaps://emea-dc01.tanflow.internal:636', bindDn: 'cn=svc_fed,ou=Service,dc=emea,dc=tanflow,dc=com', bindPassword: 'stored' },
    schedule: 'Every 15 minutes',
    matchKey: 'username',
    status: 'Healthy',
    users: 846,
    lastSyncMins: 7,
    createdOn: '2026-01-28',
    createdBy: 'SHUBHAM_JAIN',
  },
  {
    id: 3,
    name: 'ENTRA_PARTNERS',
    displayName: 'Partner Entra ID (B2B)',
    description: 'Guest identities invited into the partner tenant, federated into the DMZ directory.',
    connector: 'msentra',
    ldapAppId: 2,
    ouDn: 'ou=people,dc=partners,dc=tanflow,dc=io',
    operations: { create: true, update: true, remove: false, updateExisting: false },
    connection: { tenantId: 'partners.onmicrosoft.com', clientId: '5d2e9a10-4c1b-4f0d-b2b1-7a6e1c0f3d21', clientSecret: 'stored', timeoutSeconds: '30' },
    schedule: 'Every 6 hours',
    matchKey: 'email',
    status: 'Degraded',
    lastError: 'Microsoft Graph throttled the last two delta queries (HTTP 429).',
    users: 312,
    lastSyncMins: 196,
    createdOn: '2026-05-04',
    createdBy: 'NEHA_MEHTA',
  },
  {
    id: 4,
    name: 'CONTRACTOR_PORTAL',
    displayName: 'Contractor Portal',
    description: 'Contractor and vendor workforce provisioned over SCIM into the contractor branch.',
    connector: 'scim',
    ldapAppId: 4,
    ouDn: 'ou=contractors,dc=tanflow,dc=com',
    operations: { create: true, update: true, remove: true, updateExisting: true },
    connection: { endpoint: 'https://contractors.tanflow.io/scim/v2', bearerToken: 'stored', timeoutSeconds: '45' },
    schedule: 'Hourly',
    matchKey: 'email',
    status: 'Healthy',
    users: 298,
    lastSyncMins: 41,
    createdOn: '2026-06-17',
    createdBy: 'SHUBHAM_JAIN',
  },
  {
    id: 5,
    name: 'LEGACY_PAYROLL',
    displayName: 'Legacy Payroll',
    description: 'Payroll staff table kept until the HRMS migration completes.',
    connector: 'mysql',
    ldapAppId: 1,
    ouDn: 'ou=people,dc=tanflow,dc=com',
    operations: { create: true, update: false, remove: false, updateExisting: false },
    connection: { host: 'payroll-db.tanflow.internal', port: '3306', database: 'payroll', username: 'idam_fed', password: 'stored', accountTable: 'payroll.staff' },
    schedule: 'Nightly at 01:00',
    matchKey: 'empCode',
    status: 'Failed',
    lastError: 'Access denied for user idam_fed@10.42.8.17 (using password: YES).',
    users: 164,
    lastSyncMins: 2890,
    createdOn: '2025-11-02',
    createdBy: 'TARA_RAO',
  },
  {
    id: 6,
    name: 'VENDOR_ONBOARDING',
    displayName: 'Vendor Onboarding API',
    description: 'Vendor staff registered through the onboarding portal API.',
    connector: 'api',
    ldapAppId: 2,
    ouDn: 'ou=people,dc=partners,dc=tanflow,dc=io',
    operations: { create: true, update: true, remove: false, updateExisting: false },
    connection: {
      baseUrl: 'https://vendors.tanflow.io/api/v2',
      getTokenAPIUrl: 'https://vendors.tanflow.io/oauth/token',
      clientId: 'tanflow-idam',
      clientSecret: 'stored',
      getTokenAPIPayload: '{ "grant_type": "client_credentials" }',
      resourcePath: '/staff',
      timeoutSeconds: '30',
    },
    schedule: 'Every 6 hours',
    matchKey: 'email',
    status: 'Paused',
    users: 57,
    lastSyncMins: 8760,
    createdOn: '2026-04-09',
    createdBy: 'SANA_GUPTA',
  },
  {
    id: 7,
    name: 'ALUMNI_RECORDS',
    displayName: 'Alumni Records',
    description: 'Former employees kept for rehire checks. Tracked here, never provisioned.',
    connector: 'none',
    ldapAppId: 6,
    ouDn: 'ou=archive,dc=tanflow,dc=com',
    operations: { create: false, update: false, remove: false, updateExisting: false },
    connection: {},
    schedule: 'Manual only',
    matchKey: 'email',
    status: 'Manual',
    users: 1420,
    lastSyncMins: null,
    createdOn: '2025-09-21',
    createdBy: 'SHUBHAM_JAIN',
  },
]
