import { useState } from 'react'
import Button from '../../components/primitives/Button'
import Field from '../../components/primitives/Field'
import Pill from '../../components/primitives/Pill'
import TextInput from '../../components/primitives/TextInput'
import ScreenGallery from './ScreenGallery'
import { AuthCard, LinkRow, MethodRow, PasswordInput } from './authParts'
import { CodeChallenge, PasskeyScreen, TotpSetup } from './mfaParts'

const BASE = '/iam/additional/mfa'

function Login({ go }) {
  const [user, setUser] = useState('')
  const [pass, setPass] = useState('')
  const [touched, setTouched] = useState(false)
  return (
    <AuthCard
      eyebrow="Sign in"
      title="Welcome!"
      sub="Please sign in to your account."
      onSubmit={() => { setTouched(true); if (user.trim() && pass) go('enrol-choose') }}
    >
      <Field label="Username or email" required error={touched && !user.trim() ? 'Enter your email or username.' : ''} htmlFor="xe-user">
        <TextInput id="xe-user" autoComplete="username" placeholder="Enter your email or username" value={user} onChange={(e) => setUser(e.target.value)} />
      </Field>
      <Field label="Password" required error={touched && !pass ? 'Enter your password.' : ''} htmlFor="xe-pass">
        <PasswordInput id="xe-pass" placeholder="Enter your password" value={pass} onChange={setPass} />
      </Field>
      <LinkRow><span /><button type="button" className="link">Forgot password?</button></LinkRow>
      <Button type="submit" variant="pri" size="lg" className="lg-submit">Login</Button>
    </AuthCard>
  )
}

const ENROL = [
  { id: 'enrol-totp', icon: 'device', title: 'TOTP app', sub: 'Enter a 6-digit code generated by an authenticator app.' },
  { id: 'enrol-passkey', icon: 'key', title: 'Passkey / FIDO2', sub: 'Use a passkey or USB FIDO2 token. This provides the highest security.' },
  { id: 'enrol-sms', icon: 'phone', title: 'SMS code', sub: 'Receive a confirmation code via SMS.' },
  { id: 'enrol-email', icon: 'mail', title: 'Email OTP', sub: 'Validates a one-time password sent to the email.' },
]

function EnrolChoose({ go }) {
  return (
    <AuthCard eyebrow="Secure your account" title="Choose how you'd like to secure your account" sub="Please choose an authentication method as a second factor.">
      <div className="lg-choose">
        {ENROL.map((m) => <MethodRow key={m.id} icon={m.icon} title={m.title} sub={m.sub} onClick={() => go(m.id)} />)}
      </div>
    </AuthCard>
  )
}

function AddAnother({ go }) {
  const active = <Pill tone="ok" dot>Active</Pill>
  return (
    <AuthCard eyebrow="Secure your account" title="Add another login method?" sub="You can configure more MFA methods for backup, or skip and continue.">
      <div className="lg-choose">
        <MethodRow icon="device" title="TOTP app" sub="Enter a 6-digit code generated by an authenticator app." disabled badge={active} />
        <MethodRow icon="key" title="Passkey / FIDO2" sub="Use a passkey or USB FIDO2 token." disabled badge={active} />
        <MethodRow icon="phone" title="SMS code" sub="Receive a confirmation code via SMS." onClick={() => go('enrol-sms')} />
        <MethodRow icon="mail" title="Email OTP" sub="Validates a one-time password sent to the email." onClick={() => go('enrol-email')} />
      </div>
      <Button variant="pri" size="lg" className="lg-submit" onClick={() => go('challenge-choose')}>No, I'm done — continue to login</Button>
    </AuthCard>
  )
}

const CHALLENGES = [
  { id: 'challenge-email', icon: 'mail', title: 'Email OTP', sub: 'Email-based one-time password.' },
  { id: 'challenge-sms', icon: 'sms', title: 'SMS authenticator', sub: 'Receive a one-time code via SMS on your phone.' },
  { id: 'challenge-totp', icon: 'device', title: 'Authenticator application', sub: 'Enter a verification code from the authenticator application.' },
  { id: 'challenge-passkey', icon: 'key', title: 'Passkey', sub: 'Use your passkey to sign in.' },
]

function ChallengeChoose({ go }) {
  return (
    <AuthCard eyebrow="Multifactor authentication" title="Select login method" sub="Choose one of the methods enrolled on your account.">
      <div className="lg-choose">
        {CHALLENGES.map((m) => <MethodRow key={m.id} icon={m.icon} title={m.title} sub={m.sub} onClick={() => go(m.id)} />)}
      </div>
    </AuthCard>
  )
}

const back = (c, id) => () => c.go(id)
const signedIn = (c) => () => { c.toast('ok', 'Signed in', 'Second factor verified.'); c.go('login') }

export const MFA_SCREENS = [
  { id: 'login', group: 'Sign in', label: 'Login', path: '/login', render: (c) => <Login {...c} /> },
  { id: 'enrol-choose', group: 'Enrolment', label: 'Choose a second factor', path: '/mfa/enroll', note: 'Shown when the sign-on policy requires MFA and nothing is enrolled yet.', render: (c) => <EnrolChoose {...c} /> },
  { id: 'enrol-totp', group: 'Enrolment', label: 'TOTP app setup', path: '/mfa/enroll/totp', note: 'Demo code 481902.', render: (c) => <TotpSetup secret="GZWU QYKD PE2U GM2R GNGX" toast={c.toast} onVerified={() => c.go('add-another')} onBack={back(c, 'enrol-choose')} /> },
  { id: 'enrol-passkey', group: 'Enrolment', label: 'Passkey registration', path: '/mfa/enroll/passkey', render: (c) => <PasskeyScreen mode="register" onDone={() => c.go('add-another')} onBack={back(c, 'enrol-choose')} /> },
  { id: 'enrol-sms', group: 'Enrolment', label: 'SMS code', path: '/mfa/enroll/sms', note: 'Resend becomes available when the timer runs out.', render: (c) => <CodeChallenge {...c} eyebrow="Set up SMS" title="SMS verification" sub="Enter the verification code we sent to your mobile number." seconds={59} icon="phone" onVerified={() => c.go('add-another')} onBack={back(c, 'enrol-choose')} backLabel="Choose a different method" /> },
  { id: 'enrol-email', group: 'Enrolment', label: 'Email OTP', path: '/mfa/enroll/email', render: (c) => <CodeChallenge {...c} eyebrow="Set up email OTP" title="Email verification" sub="Enter the 6-digit verification code sent to your email." seconds={32} icon="mail" onVerified={() => c.go('add-another')} onBack={back(c, 'enrol-choose')} backLabel="Choose a different method" /> },
  { id: 'add-another', group: 'Enrolment', label: 'Add another login method?', path: '/mfa/enroll', note: 'Methods already enrolled are shown as active.', render: (c) => <AddAnother {...c} /> },
  { id: 'challenge-choose', group: 'Challenge', label: 'Select login method', path: '/mfa/challenge', note: 'Returning sign-in with several factors enrolled.', render: (c) => <ChallengeChoose {...c} /> },
  { id: 'challenge-email', group: 'Challenge', label: 'Email OTP', path: '/mfa/challenge/email', render: (c) => <CodeChallenge {...c} title="Email verification" sub="Enter the 6-digit code sent to your email." seconds={48} icon="mail" onVerified={signedIn(c)} onBack={back(c, 'challenge-choose')} /> },
  { id: 'challenge-sms', group: 'Challenge', label: 'SMS authenticator', path: '/mfa/challenge/sms', render: (c) => <CodeChallenge {...c} title="SMS verification" sub="Enter the verification code we sent to your mobile number." seconds={57} icon="sms" onVerified={signedIn(c)} onBack={back(c, 'challenge-choose')} /> },
  { id: 'challenge-totp', group: 'Challenge', label: 'Authenticator application', path: '/mfa/challenge/totp', render: (c) => <CodeChallenge {...c} title="Multifactor authentication" sub="Enter the TOTP verification code." button="Verify OTP" icon="device" onVerified={signedIn(c)} onBack={back(c, 'challenge-choose')} /> },
  { id: 'challenge-passkey', group: 'Challenge', label: 'Passkey', path: '/mfa/challenge/passkey', render: (c) => <PasskeyScreen mode="signin" created="Sep 15, 2026, 5:57 PM" onDone={() => c.go('login')} onBack={back(c, 'challenge-choose')} backLabel="Try another way" /> },
]

export default function MfaEnrolmentPage({ segments }) {
  return (
    <ScreenGallery
      base={BASE}
      title="MFA Enrolment & Challenge"
      sub="Enrolling a second factor (TOTP, passkey, SMS, email) and choosing a factor at sign-in."
      screens={MFA_SCREENS}
      segments={segments}
    />
  )
}
